### PR TITLE
Tolerate i64 call indirect

### PR DESCRIPTION
**Pull request by matthias-blume**
This change lets the validator accept i64 indices.

Notice that this modification does not conform with the current WASM spec, so we cannot upstream it.
Eventually a 64-bit table version will land, coming from upstream, at which point we can remove our local hack.

### CODE REVIEW

**Comment by matthias-blume** [comment]
I need to protect this with --no-sandbox to avoid breaking tests.

**Comment by matthias-blume** [comment]
This should be ready to go now (after the sandbox-feature PR).

**Review by dimitry- — COMMENTED** [review]
can you rebase it? It has a lot of duplicated code.

**Comment by matthias-blume** [comment]
I tried to rebase but it looks like all the changes from the other PR are still there.  (I guess something like diffbase is needed, but I don't know how that is done.)

**Comment by matthias-blume** [comment]
This is good to go now.

**Review by dimitry- — APPROVED** [review]

**Pull request merged**
