### PR TITLE
Export names are written without prefix in no-sandbox mode.

### PR DESCRIPTION
**Pull request by matthias-blume**
Plus some other minor cleanup.

There is still some unnecessary stuff being written into the .h file.  But fixing this will require separating the write logic from some data structure initialization (which in turn is needed later).

### CODE REVIEW

**Comment by matthias-blume** [comment]
Something isn't quite right.  Seems like ExportName is used in a few places where it shouldn't actually be used.  This results in invalid output because some symbols end up with numeric prefixes.

**Comment by matthias-blume** [comment]
> Something isn't quite right. Seems like ExportName is used in a few places where it shouldn't actually be used. This results in invalid output because some symbols end up with numeric prefixes.

The ExportName method seems to be called in places where the argument is not really an "export".  So I reverted the change to this (these) method(s) and limited the modification to just the WriteExports method.

**Review by dimitry- — APPROVED** [review]
lgtm

**Comment by matthias-blume** [comment]
Tests are still failing because of the way (assert_return (invoke "foo" ...)) is being rendered.  It still uses the prefixed name.  In no-sandbox mode I need to change it so that it uses the plain (unprefixed, unmangled) name.
I'm not quite sure where this thing is handled, though.

**Comment by matthias-blume** [comment]
I decided that the solution is to use #define, making the mangled name an alias of the real name.  This way any internal references of the mangled name (for example in tests) will be redirected to the real name.

**Pull request merged**
